### PR TITLE
Add file upload notifications

### PR DESCRIPTION
**Pull request by marcosnils**
This PR adds visual feedback when uploading files

Success upload: 

image

Error upload: 
image

### CODE REVIEW

**Comment by myitcv** [comment]
If we get some sort of notification via the terminal that a file upload is successful, and the block itself changes background colour with the "tick", I don't think we need another visual notification. Otherwise things will get too busy. Thoughts?

**Comment by marcosnils** [comment]
> If we get some sort of notification via the terminal that a file upload is successful,

Agree but I wasn't thinking about adding a terminal notification though.. The block background color will always show as "executed" regardless of the output. This visual feedback helps to know if the upload was successful or not. 

We might have an issue when uploading files for some reason and this can help people to open issues if that's the case.

**Comment by myitcv** [comment]
> Agree but I wasn't thinking about adding a terminal notification/feedback for this though.

As I mentioned on our call, I think we need this though. Reason being, otherwise you can't see in the sequence of events on the right hand side when you uploaded a file. Which means you need to refer back to the left hand side to cross reference. That feels like a needless break in the workflow.

If instead, a comment is "run" in the right hand side after a successful upload, something like:

```
$ # uploaded version of hello.go with random greeting support
```

then:

a) the user knows the file was successfully uploaded
b) that "notification" happens in the same place as where commands are run (with their success or otherwise)
c) the terminal window reflects a real log of what the user did when

Hence why I was thinking that a popup notification that says "upload successful" was superfluous. Because I see the terminal "notification" as key for a couple of reasons.

**Comment by marcosnils** [comment]
> As I mentioned on our call, I think we need this though. Reason being, otherwise you can't see in the sequence of events on the right hand side when you uploaded a file. Which means you need to refer back to the left hand side to cross reference. That feels like a needless break in the workflow.

Sounds good and makes sense, let's do it this way. What happens if the file fails to upload? Should we print #file <filename> failed to upload in the terminal? Would this be a bit confusing?

**Comment by myitcv** [comment]
> What happens if the file fails to upload? 

That's when I think we need the red popup you're proposing here. That would work well

**Comment by marcosnils** [comment]
> That's when I think we need the red popup you're proposing here. That would work well

Done @myitcv

**Comment by myitcv** [comment]
Will take a look ASAP

**Pull request merged**
