### PR TITLE
Add docker-compose file to build website

### PR DESCRIPTION
**Pull request by marcosnils**
This compose file should be used with this documentation
https://github.com/play-with-go/play-with-go/wiki/Building-and-deploying-the-website
to generate and publish the webiste

### CODE REVIEW

**Review by myitcv — COMMENTED** [review]
We should add this as a step in CI to ensure that each commit is "valid" and clean.

Does running `jekyll build -d docs` clean the target first? Or in CI do we need to remove the target first?

**Comment by myitcv** [comment]
Also feels like this needs to be supplemented in some way with production-specific config?

**Comment by marcosnils** [comment]
> Does running `jekyll build -d docs` clean the target first? Or in CI do we need to remove the target first?

It's incremental build..so we shouldn't remove the target first


> We should add this as a step in CI to ensure that each commit is "valid" and clean.

SGTM!


> Also feels like this needs to be supplemented in some way with production-specific config?

Hmm indeed.. let me check how I can override those flags in this compose file.

**Review by myitcv — APPROVED** [review]
LGTM

**Pull request merged**
