### PR TITLE
Refactor auth flow to allow log in in the terminal

### PR DESCRIPTION
**Pull request by marcosnils**
This PR refactors the authn flow so users can actually see the guides
and only log in when they want to see the terminal.

I've also removed the current index.html page since it's not required
anymore

Since setting this up locally is a bit complex, here's a video about how it looks

@myitcv shall we add a better message to the log in tittle? I wasn't entirely sure what to add there.

https://user-images.githubusercontent.com/1578458/107897002-badde500-6f16-11eb-83dc-2e8a3f2b8b45.mp4

### CODE REVIEW

**Comment by myitcv** [comment]
This looks awesome. Let's discuss in more detail tomorrow

**Comment by myitcv** [comment]
Re the title: yes, let's also think about how/where we provide a link that explains why we need people to login.

The title could be something "snappy" like: "Login to go interactive!"?

Also, if https://play-with-go.dev/guides.html effectively becomes the homepage, could we switch from using the Gopher eyes to having the official PWG image on that page?

**Comment by marcosnils** [comment]
> The title could be something "snappy" like: "Login to go interactive!"?

Like it. Let's decide tomorrow :muscle: 



> Also, if https://play-with-go.dev/guides.html effectively becomes the homepage, could we switch from using the Gopher eyes to having the official PWG image on that page?

Done! :)

**Review by myitcv — APPROVED** [review]
LGTM

**Pull request merged**
